version: 0.0
Resources:
  - InventoryAllocationTest2:
      Type: AWS::Lambda::Function
      Properties:
        Name: "InventoryAllocationTest2"
        Alias: "test2"
        CurrentVersion: "{{CurrentVersion}}"
        TargetVersion: "{{TargetVersion}}"
