version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - zip -r InventoryTest1.zip ./
      - aws s3 cp InventoryTest1.zip s3://codebuild-inventory-test1/BackendSource/
