AWSTemplateFormatVersion: '2010-09-09'
Description: 'FastAPI application on AWS Lambda'

Parameters:
  ParameterFilePath:
    Type: String
    Default: 's3://my-parameter-bucket/LambdaParameters.json'
    Description: 'パラメータファイルのパス'
  VpcEndpointIds:
    Type: CommaDelimitedList
    Default: ''
    Description: 'VPCエンドポイントのIDのリスト'

Resources:
  # FastAPIアプリケーションを実行するLambda関数
  FastAPIFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'FastAPIFunction'
      Runtime: 'python3.8'
      Handler: 'main.handler'
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Environment:
        Variables:
          PARAMETER_FILE_PATH: !Ref ParameterFilePath
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 128
      FunctionRegion: 'ap-northeast-1'

  # Lambda関数の実行に必要なIAMロール
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                Resource: !Sub 'arn:aws:s3:::my-parameter-bucket/LambdaParameters.json'

  # API Gatewayの定義
  APIGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: 'FastAPIGateway'
      EndpointConfiguration:
        Types:
          - REGIONAL
        VpcEndpointIds: !Ref VpcEndpointIds

  # Cognito User Poolsを使用したAPIリクエストの認証
  APIGatewayAuthorizer:
    Type: 'AWS::ApiGateway::Authorizer'
    Properties:
      Name: 'CognitoAuthorizer'
      Type: 'COGNITO_USER_POOLS'
      ProviderARNs:
        - !Ref CognitoUserPoolArn
      RestApiId: !Ref APIGateway
      IdentitySource: 'method.request.header.Authorization'

  # API Gatewayのリソース定義
  APIGatewayResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt APIGateway.RootResourceId
      PathPart: '{proxy+}'
      RestApiId: !Ref APIGateway

  # API Gatewayのメソッド定義とLambda関数との統合
  APIGatewayMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: ANY
      ResourceId: !Ref APIGatewayResource
      RestApiId: !Ref APIGateway
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref APIGatewayAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${FastAPIFunction.Arn}/invocations'

  # API Gatewayの変更をデプロイ
  APIGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - APIGatewayMethod
    Properties:
      RestApiId: !Ref APIGateway
      StageName: !Ref APIGatewayStageName

Outputs:
  # API GatewayのエンドポイントURLを出力
  APIGatewayInvokeURL:
    Description: 'API GatewayのエンドポイントURL'
    Value: !Sub 'https://${APIGateway}.execute-api.ap-northeast-1.amazonaws.com/${APIGatewayStageName}'
