AWSTemplateFormatVersion: '2010-09-09'
Description: 'FastAPI application on AWS Lambda'

Parameters:
  ParameterFilePath:
    Type: String
    Default: 's3://lxj-parameter-bucket/LambdaParameters.json'
    Description: 'パラメータファイルのパス'

  CognitoUserPoolArn:
    Type: String
    Default: "arn:aws:cognito-idp:ap-northeast-1:047403811176:userpool/ap-northeast-1_z3MqPKbu0"
  
  CognitoUserPoolClientId:
    Type: String
    Default: "78rpor87694sq6rb6ls303fg2t"

  LambdaCodeBucket:
    Type: String
    Default: "lxj-lambda-code-bucket"

  LambdaCodeKey:
    Type: String
    Default: "fastapi-app/lambda_function.zip"

  VpcId:
    Type: String
    Default: "vpc-004ca6b3f43853a73"

  PrivateSubnet1Id:
    Type: String
    Default: "subnet-02186b55eec727376"

  PrivateSubnet2Id:
    Type: String
    Default: "subnet-0eeae32c2476abc31"

  APIGatewayStageName:
    Type: String
    Default: "dev"

Resources:
  # FastAPIアプリケーションを実行するLambda関数
  FastAPIFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'FastAPIFunction'
      Runtime: 'python3.9'
      Handler: 'main.handler'
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Environment:
        Variables:
          PARAMETER_FILE_PATH: !Ref ParameterFilePath
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 128

  # Lambda関数の実行に必要なIAMロール
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                Resource: !Sub 'arn:aws:s3:::lxj-parameter-bucket/LambdaParameters.json'

  # VPCエンドポイント1の定義
  VPCEndpoint1:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.execute-api'
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet1Id

  # VPCエンドポイント2の定義
  VPCEndpoint2:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.execute-api'
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet2Id

  # API Gatewayの定義
  APIGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: 'FastAPIGateway'
      EndpointConfiguration:
        Types:
          - PRIVATE
        VpcEndpointIds: 
          - !Ref VPCEndpoint1
          - !Ref VPCEndpoint2
      Policy:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "execute-api:Invoke"
            Resource: "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/*"
            Condition:
              StringEquals:
                aws:SourceVpce:
                  - !Ref VPCEndpoint1
                  - !Ref VPCEndpoint2

  # Cognito User Poolsを使用したAPIリクエストの認証
  APIGatewayAuthorizer:
    Type: 'AWS::ApiGateway::Authorizer'
    Properties:
      Name: 'CognitoAuthorizer'
      Type: 'COGNITO_USER_POOLS'
      ProviderARNs:
        - !Ref CognitoUserPoolArn
      RestApiId: !Ref APIGateway
      IdentitySource: 'method.request.header.Authorization'

  # API Gatewayのリソース定義
  APIGatewayResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt APIGateway.RootResourceId
      PathPart: '{proxy+}'
      RestApiId: !Ref APIGateway

  # API Gatewayのメソッド定義とLambda関数との統合
  APIGatewayMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: ANY
      ResourceId: !Ref APIGatewayResource
      RestApiId: !Ref APIGateway
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref APIGatewayAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${FastAPIFunction.Arn}/invocations'

  # API Gatewayの変更をデプロイ
  APIGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - APIGatewayMethod
    Properties:
      RestApiId: !Ref APIGateway
      StageName: !Ref APIGatewayStageName

Outputs:
  # API GatewayのエンドポイントURLを出力
  APIGatewayInvokeURL:
    Description: 'API GatewayのエンドポイントURL'
    Value: !Sub 'https://${APIGateway}.execute-api.ap-northeast-1.amazonaws.com/${APIGatewayStageName}'
